[project]
name = 'Decentralized-Clinical-Trial-Patient-Matching'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consent-management]
path = 'contracts/consent-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.matching-algorithm]
path = 'contracts/matching-algorithm.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-profile]
path = 'contracts/patient-profile.clar'
clarity_version = 2
epoch = 2.5

[contracts.trial-criteria]
path = 'contracts/trial-criteria.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
